### ISSUE TITLE
Can't include arity-n via Webpack

### ISSUE THREAD

**Issue by aknuds1** [stoeffel/arityN#1]
I can't include underscore.string.fp via Webpack, since the inclusion of arity-n fails like this:

```
WARNING in ./~/underscore.string.fp/~/compose-function/~/arity-n/package.json Module parse failed: 
/Users/arve/Projects/gradlehub/node_modules/underscore.string.fp/node_modules/compose-function/node_modules/arity-n/package.json Line 2: 
Unexpected token : You may need an appropriate loader to handle this file type.
{
    "name": "arity-n",
    "version": "1.0.3",
    "description": "Wraps a function with a function of a sertain arity.",
@ ./~/underscore.string.fp/~/compose-function/~/arity-n ^\.\/.*$
```

What happens here is that Webpack tries to parse package.json (as well as README.md, LICENSE and test.js), which are files that shouldn't be considered for bundling.

**Comment by stoeffel** [comment]
I updated underscore.string.fp. Can you test it again with 1.0.4?

**Comment by stoeffel** [comment]
The problem was that I required 0-5.js dynamically in N.js

**Comment by aknuds1** [comment]
Yep, works perfectly now, thanks!

**Comment by stoeffel** [comment]
np. Always nice to see that someone is using my modules
